language: java
# use Java 8
jdk: oraclejdk8

# faster build, see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

# improve build speed with cache
cache:
  directories:
  - $HOME/.m2

install: true
script:
  - mvn clean package -P ossrh-release
